### ISSUE TITLE
Can't convert. "Error in LoadLibraryA"

### ISSUE THREAD

**Issue by JettFlat** [MortenHannemose/pytorch-vfi-cft#12]
Hi, i tryied to convert default example, but I've got this exception. (Win10)
```
D:\WORK\VideFramesDrawer\pytorch-vfi-cft-master>python slow_movie.py -m rain.mp4
  0%|                                                                                           | 0/36 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "slow_movie.py", line 110, in <module>
    SlowMovie(args.movie_path, args.slow_factor, args.continuous_fine_tuning)
  File "slow_movie.py", line 83, in SlowMovie
    compute_inbetween_frames(real_frames, 1)
  File "slow_movie.py", line 60, in compute_inbetween_frames
    recursive_predict_and_write(frame0, frame1, frame0_no*slow_factor, slow_factor)
  File "slow_movie.py", line 24, in recursive_predict_and_write
    f1 = net(f0, f2)['output_im']
  File "D:\Soft\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\WORK\VideFramesDrawer\pytorch-vfi-cft-master\network.py", line 89, in forward
    var_join_input = torch.cat([input0, input2], dim=1)
RuntimeError: error in LoadLibraryA
```
How fix?

**Comment by MortenHannemose** [comment]
Googling the error finds [other people](https://stackoverflow.com/questions/60478862/how-to-avoid-runtimeerror-error-in-loadlibrarya-for-torch-cat) that have solved this issue by downgrading to Python 3.7.6
