### ISSUE TITLE
Having an issue running this on ubuntu 18.04 LTS on GCP

### ISSUE THREAD

**Issue by deama** [MortenHannemose/pytorch-vfi-cft#8]
So I span up a GCP virtual machine on google servers with an Ubuntu OS, nice fresh copy.

Here are the commands I run:
git clone https://github.com/MortenHannemose/pytorch-vfi-cft.git
sudo apt update
sudo apt install python3-pip
pip install torch==1.1.0 torchvision==0.3.0
pip3 install opencv-python
sudo apt install ffmpeg

python is installed by default, version 3.6.9.

I then go to your google drive and manually download the weights, put them in the pytorch git folder, then try to run it:
python3 slow_movie.py -m rain.mp4 -f 2

However I get the following error:

python3: Relink `/lib/x86_64-linux-gnu/libsystemd.so.0' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
python3: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
Segmentation fault (core dumped)

And using some sort of gdb moudle for debuggin yields:
#131 0x000000000050aa7d in ?? ()
#132 0x000000000050c5b9 in _PyEval_EvalFrameDefault ()
#133 0x0000000000509d48 in ?? ()
#134 0x000000000050aa7d in ?? ()
#135 0x000000000050c5b9 in _PyEval_EvalFrameDefault ()
#136 0x0000000000509d48 in ?? ()
#137 0x000000000050aa7d in ?? ()
#138 0x000000000050c5b9 in _PyEval_EvalFrameDefault ()
#139 0x0000000000509d48 in ?? ()
#140 0x000000000050aa7d in ?? ()
#141 0x000000000050c5b9 in _PyEval_EvalFrameDefault ()
---Type <return> to continue, or q <return> to quit---
#142 0x0000000000509455 in _PyFunction_FastCallDict ()
#143 0x00000000005a55a1 in _PyObject_FastCallDict ()
#144 0x00000000005a65de in _PyObject_CallMethodIdObjArgs ()
#145 0x00000000004f729d in PyImport_ImportModuleLevelObject ()
#146 0x0000000000514804 in ?? ()
#147 0x00000000005678b3 in PyCFunction_Call ()
#148 0x000000000051171e in _PyEval_EvalFrameDefault ()
#149 0x0000000000508245 in ?? ()
#150 0x000000000050a080 in ?? ()
#151 0x000000000050aa7d in ?? ()
#152 0x000000000050c5b9 in _PyEval_EvalFrameDefault ()
#153 0x0000000000509d48 in ?? ()
#154 0x000000000050aa7d in ?? ()
#155 0x000000000050c5b9 in _PyEval_EvalFrameDefault ()
#156 0x0000000000509455 in _PyFunction_FastCallDict ()
#157 0x00000000005a55a1 in _PyObject_FastCallDict ()
#158 0x00000000005a65de in _PyObject_CallMethodIdObjArgs ()
#159 0x00000000004f729d in PyImport_ImportModuleLevelObject ()
#160 0x000000000050e4f1 in _PyEval_EvalFrameDefault ()
#161 0x0000000000509455 in _PyFunction_FastCallDict ()
#162 0x00000000005a55a1 in _PyObject_FastCallDict ()
#163 0x00000000006386cb in PyErr_PrintEx ()
#164 0x0000000000638ab3 in PyRun_SimpleFileExFlags ()
#165 0x0000000000639631 in Py_Main ()
#166 0x00000000004b0f40 in main ()

Any ideas? There is no GPU attached, I'm trying to get it to run via CPU, is that possible? Anyway, it should give me an entirely different error than that I think.

**Comment by deama** [comment]
Ah, nvm, fixed it by using the debian deep learning GCP image.
